spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true

elasticsearch:
  host: localhost
  port: 9200
  schema: http

logging:
  level:
    org.elasticsearch.client.RestClient: ERROR